---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tektutortasks.training.tektutor.org
spec:
  group: training.tektutor.org
  names:
    kind: TekTutorTask
    listKind: TekTutorTaskList
    plural: tektutortasks
    singular: tektutortask
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: TekTutorTask is the Schema for the tektutortasks API
        properties:
          apiVersion: 
            type: string
          kind: 
            type: string
          spec:
            properties:
              message:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
