apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-jegan #Replace 'jegan' with your name
  namespace: jegan  #Replace this with your project name
spec:
  selector:
    matchLabels:
      name: jegan  #Replace this with your name
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
