# PipelineRun - provides all required parameters to the Pipeline while running
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: java-tekton-cicd-pipeline-run-
spec:
  pipelineRef:
    name: java-tekton-cicd-pipeline
  serviceAccountName: pipeline 
  workspaces:
  - name: source-code
    persistentVolumeClaim:
      claimName: tekton-pvc-jegan  # Replace 'jegan' with your name
    subPath: source
  - name: maven-repo 
    persistentVolumeClaim:
      claimName: tekton-pvc-jegan  # Replace 'jegan' with your name
    subPath: settings 
