# Reserve 500MB disk space for Persistent Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.80 # Replace this with your server IP 192.168.1.207 or 192.168.1.208
    path: "/mnt/tekton" # If your centos user is user1 then folder will be /mnt/user1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc-jegan # Replace 'jegan' with your name
  labels:
    name: jegan # Replace 'jegan' with your name
spec:
  selector:
    matchLabels:
      name: jegan # Replace 'jegan' with your name
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: java-tekton-cicd-pipeline
spec:
  workspaces:
  - name: source-code
  - name: maven-repo
  tasks:
  - name: clone-git-repo
    params: 
    - name: url
      value: 'https://github.com/tektutor/hello-spring-boot.git'
    - name: revision
      value: main
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: source-code

  - name: compile
    params:
    - name: GOALS
      value:
      - -Dmaven.repo.local=$(workspaces.maven-settings.path)
      - clean
      - compile
    runAfter:
    - clone-git-repo
    taskRef:
      name: maven
    workspaces:
    - name: source
      workspace: source-code
    - name: maven-settings
      workspace: maven-repo

  - name: unit-test 
    params:
    - name: GOALS
      value:
      - -Dmaven.repo.local=$(workspaces.maven-settings.path)
      - test 
    runAfter:
    - compile
    taskRef:
      name: maven
    workspaces:
    - name: source
      workspace: source-code
    - name: maven-settings
      workspace: maven-repo

  - name: package 
    params:
    - name: GOALS
      value:
      - -Dmaven.repo.local=$(workspaces.maven-settings.path)
      - package 
    runAfter:
    - unit-test 
    taskRef:
      name: maven
    workspaces:
    - name: source
      workspace: source-code
    - name: maven-settings
      workspace: maven-repo
