# permissions for end users to edit tektutortasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tektutortask-editor-role
rules:
- apiGroups:
  - training.tektutor.org
  resources:
  - tektutortasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.tektutor.org
  resources:
  - tektutortasks/status
  verbs:
  - get
