apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: books.tektutor.org 
spec:
  group: tektutor.org 

  scope: Namespaced
  names:
    kind: Book 
    listKind: BookList
    plural: books 
    singular: book 
    shortNames:
    - bk 

  versions:
    - name: v1
      served: true
      storage: true 
      schema:
        openAPIV3Schema:
          type: object
          properties:
              name:
                type: string
              author:
                type: string
              publisher:
                type: string
