apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: hello-taskrun-v1-
spec:
  params:
  - name: msg1
    value: "Taskrun message 1"
  - name: msg2
    value: "Taskrun message 2"
  taskSpec:
    params:
    - name: msg1
      type: string
    - name: msg2
      type: string
    steps:
    - name: step1
      image: ubuntu
      script: |
        echo $(params.msg1)
        echo $(params.msg2)

