apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: task-with-secrets-
spec:
  workspaces:
  - name: openshift-credentials
    secret:
      secretName: openshift-login-credentials
      items:
      - key: username
        path: username.txt
      - key: password
        path: password.txt
  taskSpec:
    steps:
    - name: c1
      image: ubuntu
      script: |
        cat $(workspaces.openshift-credentials.path)/username.txt
        echo -e "\n"
        cat $(workspaces.openshift-credentials.path)/password.txt
    workspaces:
    - name: openshift-credentials
      mountPath: /my/secrets
